apiVersion: v1
kind: Pod
metadata:
  name: httpd-with-resources
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 50Mi